import rehypeGenerateYaml from "./plugins/rehype-generate-yaml.js"
import nextBundleAnalyzer from "@next/bundle-analyzer"
import nextMDX from "@next/mdx"
import ESLintPlugin from "eslint-webpack-plugin"
import fs from "fs"
import JSON5 from "json5"
import rehypePrettyCode from "rehype-pretty-code"
import remarkGfm from "remark-gfm"
import remarkSmartypants from "remark-smartypants"
import { createLoader } from "simple-functional-loader"

const withBundleAnalyzer = nextBundleAnalyzer({
  enabled: process.env.ANALYZE === "true",
})

// const basePath = "/preview"
const basePath = ""

const steepColorTheme = JSON5.parse(
  fs.readFileSync("./components/lib/steep-color-theme.json", "utf8"),
)
const withMDX = nextMDX({
  extension: /\.mdx?$/,
  options: {
    remarkPlugins: [remarkGfm, remarkSmartypants],
    rehypePlugins: [
      rehypeGenerateYaml,
      [
        rehypePrettyCode,
        {
          theme: steepColorTheme,
          keepBackground: false,
        },
      ],
    ],
  },
})

const config = {
  // also render markdown pages
  pageExtensions: ["js", "jsx", "ts", "tsx", "md", "mdx"],

  // create a folder for each page
  trailingSlash: true,

  // export static website
  output: "export",

  // configure base path
  basePath,
  assetPrefix: basePath === "" ? undefined : basePath,

  eslint: {
    dirs: ["app", "components", "content", "pages", "plugins"],
  },

  images: {
    // disable built-in image support
    disableStaticImages: true,
  },

  modularizeImports: {
    lodash: {
      transform: "lodash/{{member}}",
      preventFullImport: true,
    },
    "simple-icons": {
      transform: "simple-icons/icons",
      preventFullImport: true,
      skipDefaultConversion: true,
    },
  },

  webpack: (config, { dev, defaultLoaders }) => {
    config.module.rules.push({
      test: /\.(gif|png|jpe?g)$/i,
      type: "asset",
      use: "image-webpack-loader",
    })

    // optimize SVGs generated by draw.io
    config.module.rules.push({
      test: /\.svg$/i,
      resourceQuery: /drawio/,
      use: [
        {
          loader: "@svgr/webpack",
          options: {
            dimensions: false,
            prettier: false, // we'll never see the code anyhow
            svgoConfig: {
              multipass: true,
              plugins: ["preset-default"],
            },
          },
        },
        createLoader(function (source) {
          // remove font-family
          source = source.replaceAll(/font-family="[^"]*"/g, "")
          source = source.replaceAll(/font-family:[^";]*;?/g, "")

          // remove useless warning
          source = source.replace("Text is not SVG - cannot display", "")

          // change black to currentColor
          source = source.replaceAll(
            /stroke="(rgb\(0,\s*0,\s*0\)|#000000|#000)"/gi,
            "stroke='currentColor'",
          )
          source = source.replaceAll(
            /fill="(rgb\(0,\s*0,\s*0\)|#000000|#000)"/gi,
            "fill='currentColor'",
          )
          source = source.replaceAll(
            /color:\s*(rgb\(0,\s*0,\s*0\)|#000000|#000)/gi,
            "color:var(--color-fg)",
          )

          return source
        }),
      ],
    })

    if (dev) {
      config.plugins.push(
        new ESLintPlugin({
          extensions: ["js", "jsx"],
        }),
      )
    }
    return config
  },
}

export default withBundleAnalyzer(withMDX(config))
