name: Build website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd src
          npm ci
          cd scraper
          npm ci

      - name: Build website
        run: |
          cd src
          npm run build
